### Criar Fruta
POST http://localhost:3000/frutas
Content-Type: application/json

{
  "nome": "Maçã",
  "preco": 5,
  "quantidadeEstoque": 10
}

###

### Buscar todas as Frutas
GET http://localhost:3000/frutas

###

### Buscar Fruta por ID
GET http://localhost:3000/frutas/1

###

### Atualizar Fruta
PUT http://localhost:3000/frutas/1
Content-Type: application/json

{
  "nome": "Maçã Fuji",
  "preco": 6.00,
  "quantidadeEstoque": 15
}

###

### Deletar Fruta
DELETE http://localhost:3000/frutas/1

###
