### Criar Pedido
POST http://localhost:3000/pedidos
Content-Type: application/json

{
  "clienteId": 1,
  "status": "Pendente",
  "valorTotal": 100.50
}

###

### Buscar todos os Pedidos
GET http://localhost:3000/pedidos

###

### Buscar Pedido por ID
GET http://localhost:3000/pedidos/1

###

### Atualizar Pedido
PUT http://localhost:3000/pedidos/1
Content-Type: application/json

{
  "status": "Finalizado",
  "valorTotal": 120.00
}

###

### Deletar Pedido
DELETE http://localhost:3000/pedidos/1

###
