### Registro de usuário
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "nomeUsuario": "yasmindev",
  "nome": "Yasmin",
  "senha": "123456",
  "email": "yasmin@gmail.com"
}

### Login de usuário
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "nomeUsuario": "yasmindev",
  "senha": "132"
}

### GET todos usuários (precisa do token)
GET http://localhost:3000/user
Authorization: Bearer {{access_token}}

### GET usuário por id (precisa do token)
GET http://localhost:3000/user/1
Authorization: Bearer {{access_token}}

### Atualizar usuário (precisa do token)
PATCH http://localhost:3000/user/1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "nome": "Yasmin Atualizada"
}

### Deletar usuário (precisa do token)
DELETE http://localhost:3000/user/1
Authorization: Bearer {{access_token}}
